# Generated by Django 5.0.2 on 2024-03-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAwareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=200)),
                ('Rating', models.FloatField()),
                ('Des', models.CharField(max_length=1000)),
                ('Installment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('schoolawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolapp.schoolawaremodel')),
                ('level', models.FloatField()),
                ('number', models.FloatField()),
            ],
            bases=('schoolapp.schoolawaremodel',),
        ),
        migrations.AddField(
            model_name='schoolawaremodel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school'),
        ),
    ]
