# Generated by Django 5.0.2 on 2024-03-05 08:21

import django.db.models.deletion
import django_resized.forms
import schoolapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_supervisor_account_and_more'),
        ('schoolapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('acceptable', 'Acceptable'), ('rejected', 'Rejected'), ('waiting', 'Waiting')], max_length=15)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Time_Quiz', models.DateTimeField()),
                ('Time_final', models.DateTimeField()),
                ('hisclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(choices=[('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], max_length=15)),
                ('time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('schoolawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolapp.schoolawaremodel')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schoolapp.schoolawaremodel',),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('schoolawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolapp.schoolawaremodel')),
                ('Des', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schoolapp.schoolawaremodel',),
        ),
        migrations.CreateModel(
            name='order_join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('acceptable', 'Acceptable'), ('rejected', 'Rejected'), ('waiting', 'Waiting')], max_length=15)),
                ('StudentName', models.CharField(max_length=50)),
                ('His_level', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth')], max_length=15)),
                ('Is_pay', models.BooleanField(default=False)),
                ('Img1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=schoolapp.models.upload_to)),
                ('Img2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=schoolapp.models.upload_to)),
                ('Img3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=schoolapp.models.upload_to)),
                ('Img4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=schoolapp.models.upload_to)),
                ('Schooljoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.school')),
                ('parentjoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Birthday', models.DateTimeField()),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=schoolapp.models.upload_to)),
                ('hisclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.class')),
                ('hisparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.parent')),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_Quiz', models.FloatField()),
                ('mark_final', models.FloatField()),
                ('mark_Works', models.FloatField()),
                ('course_Mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
                ('student_Mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Activites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('healthy', 'Healthy'), ('sport', 'Sport'), ('intellectual', 'Intellectual'), ('general', 'General')], max_length=15)),
                ('level', models.CharField(max_length=15)),
                ('Des', models.CharField(max_length=100)),
                ('Student_active', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentINCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True)),
                ('Date', models.DateTimeField()),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('schoolawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolapp.schoolawaremodel')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schoolapp.schoolawaremodel',),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.supervisor'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('schoolawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolapp.schoolawaremodel')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schoolapp.schoolawaremodel',),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Des', models.CharField(max_length=150)),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.teacher'),
        ),
    ]
