# Generated by Django 5.0.2 on 2024-04-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_remove_school_password_adminschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminschool',
            name='Competence',
        ),
    ]
