# Generated by Django 5.0.2 on 2024-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_remove_adminschool_competence'),
    ]

    operations = [
        migrations.AddField(
            model_name='excourses',
            name='type',
            field=models.CharField(default='math', max_length=100),
            preserve_default=False,
        ),
    ]
