# Generated by Django 5.0.2 on 2024-04-12 13:43

import django.db.models.deletion
import django_resized.forms
import schoolapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_excourses_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=schoolapp.models.upload_to)),
                ('Des', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=100)),
                ('locationName', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('schoolawaremodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schoolapp.schoolawaremodel')),
                ('Des', models.CharField(max_length=1000)),
            ],
            bases=('schoolapp.schoolawaremodel',),
        ),
    ]
