# Generated by Django 5.0.2 on 2024-04-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_location_alter_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
