# Generated by Django 5.0.2 on 2024-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0009_location_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_join',
            name='StudentBirthday',
            field=models.DateTimeField(default='2002-01-01 22:11:11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_join',
            name='Studentgender',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], default='boy', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('girl', 'girl'), ('boy', 'boy')], default='boy', max_length=200),
            preserve_default=False,
        ),
    ]
