# Generated by Django 5.0.2 on 2024-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='identity',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='Parent', max_length=15),
            preserve_default=False,
        ),
    ]
