# Generated by Django 5.0.2 on 2024-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default=1234567, max_length=15),
            preserve_default=False,
        ),
    ]
