# Generated by Django 5.0.2 on 2024-04-05 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='Account.account'),
        ),
    ]
