# Generated by Django 5.0.2 on 2024-03-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_employee_parent_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='account',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='schoolawaremodel_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='account',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schoolawaremodel_ptr',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
