# Generated by Django 5.0.2 on 2024-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_parent_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identity',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('admin', 'Admin')], max_length=15),
        ),
    ]
