# Generated by Django 5.0.2 on 2024-04-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_account_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Workname',
            field=models.CharField(default='m', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.CharField(default='m', max_length=30),
            preserve_default=False,
        ),
    ]
